newton on
boundary	 	 p p p
units	 	 	 metal
atom_style	 	 atomic

read_data lattice.xyz

neighbor    0.01 bin
neigh_modify once yes
pair_style morse 2.5
#param1: 1.694400
#param2: 1.285100
pair_coeff 1 1 1 1 1 
pair_coeff 2 2 1 1 1
pair_coeff 1 2 1.694400 1.285100 2.120500

# Initialize velocity, thermo settings, timestep and ensemble
velocity	 all create 1000 20101 rot yes mom yes
thermo  	 100
thermo_style custom step pe temp #ke press vol temp
fix 1 all nve
timestep  0.0005

# Run MD	 	 	 	 	  
dump 1 all xyz 100 dump.xyz	
dump 2 all custom 100 dump.forces fx fy fz 
#dump 3 all custom 1 dump.coords type xs ys zs
#dump_modify 3 format float %20.15g scale yes
dump_modify 2 sort id
run 1000000
unfix 1
undump 1

#write_data Si.data
