#!/bin/bash
# Acceptance test for VASP
# Assumes 8 procs and 1gb/core
#PBS -N run_vasp_serial
#PBS -l nodes=1:ppn=4
#PBS -l pmem=4gb
#PBS -l walltime=12:00:00
#PBS -q iw-shared-6    

module purge
module load intel/15.0
module load openmpi/1.8
module load fftw/3.3.4
module load mkl/11.2
module load vasp/5.3.3
module load octave/3.6.1


cd ${PBS_O_WORKDIR}


chmod +x kpoints_sweep.sh
./kpoints_sweep.sh
